/**
 * Global wrapper provisioning — ensures `agent-tempo` is runnable from any
 * shell without requiring `npx` or manual PATH surgery.
 *
 * **Strategy**: Write a thin wrapper script into `~/.agent-tempo/bin/` that
 * reads an entrypoint pointer file (`.entrypoint`) to locate the real
 * `dist/cli.js`. Every successful CLI boot refreshes the pointer so
 * reinstalls (npm, pnpm, yarn — any package manager) auto-heal without
 * user intervention.
 *
 * Cross-platform: emits a POSIX shell script + a `.cmd` for Windows.
 *
 * **Non-breaking**: If `agent-tempo` already resolves on PATH to a location
 * outside `~/.agent-tempo/bin/` (e.g. npm global install), the wrapper is
 * still written but the PATH hint is suppressed.
 */
import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync, renameSync } from 'fs';
import { join, resolve } from 'path';
import { homedir } from 'os';

/** Resolved CLI entrypoint — the `dist/cli.js` of the running binary. */
const THIS_CLI_JS = resolve(__dirname, '..', 'cli.js');

/**
 * Wrapper bin directory. Lives inside the agent-tempo home so it follows
 * the same dev-mode / home-override semantics, but we hardcode `~/.agent-tempo`
 * here because the wrapper must be stable across dev/prod modes — it's a
 * user-facing PATH entry that shouldn't move.
 */
function getWrapperBinDir(): string {
  return join(homedir(), '.agent-tempo', 'bin');
}

const ENTRYPOINT_FILENAME = '.entrypoint';

// ─── Unix wrapper ────────────────────────────────────────────────────────

/* eslint-disable no-useless-escape */
const UNIX_WRAPPER = [
  '#!/bin/sh',
  '# Auto-generated by agent-tempo. Do not edit manually.',
  '# This wrapper resolves the agent-tempo CLI entrypoint dynamically so',
  '# reinstalls (npm/pnpm/yarn) auto-heal without re-linking.',
  'set -e',
  'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"',
  `ENTRYPOINT_FILE="\${SCRIPT_DIR}/${ENTRYPOINT_FILENAME}"`,
  'if [ ! -f "$ENTRYPOINT_FILE" ]; then',
  '  echo "agent-tempo: entrypoint not configured. Run \'npx agent-tempo\' once to repair." >&2',
  '  exit 1',
  'fi',
  'ENTRYPOINT="$(cat "$ENTRYPOINT_FILE")"',
  'if [ ! -f "$ENTRYPOINT" ]; then',
  '  echo "agent-tempo: entrypoint stale ($ENTRYPOINT). Run \'npx agent-tempo\' once to repair." >&2',
  '  exit 1',
  'fi',
  'exec node "$ENTRYPOINT" "$@"',
  '',
].join('\n');

// ─── Windows wrapper ─────────────────────────────────────────────────────

const WIN_WRAPPER = [
  '@echo off',
  'rem Auto-generated by agent-tempo. Do not edit manually.',
  'setlocal enabledelayedexpansion',
  'set "SCRIPT_DIR=%~dp0"',
  `set "ENTRYPOINT_FILE=%SCRIPT_DIR%${ENTRYPOINT_FILENAME}"`,
  'if not exist "%ENTRYPOINT_FILE%" (',
  '  echo agent-tempo: entrypoint not configured. Run "npx agent-tempo" once to repair. >&2',
  '  exit /b 1',
  ')',
  'set /p ENTRYPOINT=<"%ENTRYPOINT_FILE%"',
  'if not exist "%ENTRYPOINT%" (',
  '  echo agent-tempo: entrypoint stale. Run "npx agent-tempo" once to repair. >&2',
  '  exit /b 1',
  ')',
  'node "%ENTRYPOINT%" %*',
  '',
].join('\r\n');

// ─── Public API ──────────────────────────────────────────────────────────

/**
 * Refresh the entrypoint pointer so the global wrapper resolves to the
 * currently-running binary. Called on every successful CLI boot — cheap
 * (one `writeFileSync`) and idempotent.
 */
export function refreshEntrypoint(): void {
  try {
    const binDir = getWrapperBinDir();
    mkdirSync(binDir, { recursive: true });
    const pointerPath = join(binDir, ENTRYPOINT_FILENAME);
    const current = safeRead(pointerPath);
    // Skip write if already correct — avoids unnecessary disk churn.
    if (current === THIS_CLI_JS) return;
    // Atomic write-then-rename: a torn `.entrypoint` would break the wrapper
    // until the next CLI boot, so stage into a tmp file and rename into place.
    // `renameSync` is atomic on POSIX and at least better-than-torn on Windows.
    const tmp = pointerPath + '.tmp';
    writeFileSync(tmp, THIS_CLI_JS, 'utf8');
    renameSync(tmp, pointerPath);
  } catch {
    // Best-effort — never throw from a convenience provisioning step.
  }
}

/**
 * Ensure the wrapper scripts exist. Called once per binary version (guarded
 * by the bootstrap cache). Returns `true` if a PATH hint should be shown
 * to the user (i.e., the bin dir is not yet on PATH).
 */
export function provisionWrapperScripts(): { created: boolean; needsPathHint: boolean } {
  try {
    const binDir = getWrapperBinDir();
    mkdirSync(binDir, { recursive: true });

    const unixPath = join(binDir, 'agent-tempo');
    const cmdPath = join(binDir, 'agent-tempo.cmd');

    let created = false;

    // Write Unix wrapper if missing or outdated.
    if (!existsSync(unixPath) || safeRead(unixPath) !== UNIX_WRAPPER) {
      writeFileSync(unixPath, UNIX_WRAPPER, { mode: 0o755 });
      created = true;
    }
    // Ensure executable even if content matches (chmod may have been lost).
    try { chmodSync(unixPath, 0o755); } catch { /* Windows — no-op */ }

    // Write Windows wrapper if missing or outdated.
    if (!existsSync(cmdPath) || safeRead(cmdPath) !== WIN_WRAPPER) {
      writeFileSync(cmdPath, WIN_WRAPPER);
      created = true;
    }

    // Write the entrypoint pointer.
    refreshEntrypoint();

    // Determine if PATH hint is needed.
    const needsPathHint = !isBinDirOnPath(binDir);

    return { created, needsPathHint };
  } catch {
    return { created: false, needsPathHint: false };
  }
}

/**
 * Returns a one-liner PATH hint appropriate for the current platform/shell.
 */
export function getPathHint(): string {
  const binDir = getWrapperBinDir();
  if (process.platform === 'win32') {
    return `Add to PATH: setx PATH "%PATH%;${binDir}"`;
  }
  // Unix — suggest the export for both bash and zsh.
  return `Add to PATH: export PATH="${binDir}:$PATH"  (add to ~/.zshrc or ~/.bashrc)`;
}

// ─── Internals ───────────────────────────────────────────────────────────

function safeRead(filePath: string): string | undefined {
  try {
    return readFileSync(filePath, 'utf8');
  } catch {
    return undefined;
  }
}

function isBinDirOnPath(binDir: string): boolean {
  const pathEnv = process.env.PATH || process.env.Path || '';
  const sep = process.platform === 'win32' ? ';' : ':';
  const dirs = pathEnv.split(sep);
  // Windows filesystem paths are case-insensitive; normalize before comparing
  // so `C:\Users\X\...` and `c:\users\x\...` don't produce a spurious PATH hint.
  const norm = (p: string) =>
    process.platform === 'win32' ? resolve(p).toLowerCase() : resolve(p);
  return dirs.some((d) => norm(d) === norm(binDir));
}
